//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MlaWebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MlaDatabaseEntities : DbContext
    {
        public MlaDatabaseEntities()
            : base("name=MlaDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Group_Invitation_Table> Group_Invitation_Table { get; set; }
        public virtual DbSet<Group_Key_Table> Group_Key_Table { get; set; }
        public virtual DbSet<Group_Status_Table> Group_Status_Table { get; set; }
        public virtual DbSet<Group_Table> Group_Table { get; set; }
        public virtual DbSet<Post_Table> Post_Table { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
